### ISSUE TITLE
Checksum errors on docker build

### ISSUE THREAD

**Issue by vfbsilva** [mdedonno1337/docker-NFIQ2#1]
Hi, I've tried to build the code with no luck.

`Sending build context to Docker daemon  199.3MB
Step 1/18 : FROM centos as builder
 ---> 67fa590cfc1c
Step 2/18 : LABEL maintainer "Marco.DeDonno@unil.ch"
 ---> Using cache
 ---> bf512cd9c7e1
Step 3/18 : ADD NFIQ2.tgz /
 ---> Using cache
 ---> ec5b51efbbfb
Step 4/18 : RUN yum clean all
 ---> Using cache
 ---> 77cb371a2c9d
Step 5/18 : RUN yum --enablerepo=base clean metadata
 ---> Running in 88250e31e32c
Loaded plugins: fastestmirror, ovl
Cleaning repos: base extras updates
0 metadata files removed
0 sqlite files removed
0 metadata files removed
Removing intermediate container 88250e31e32c
 ---> ddc9fc5bea1a
Step 6/18 : RUN yum update &&     yum upgrade -y
 ---> Running in 5ad8a6f1da45
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
 * base: centos.brnet.net.br
 * extras: linorg.usp.br
 * updates: linorg.usp.br
http://linorg.usp.br/CentOS/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum                                                                                            
Trying other mirror.                                                                                                                           
http://centos.usetelecom.com.br/centos/7.6.1810/os/x86_64/repodata/6614b3605d961a4aaec45d74ac4e5e713e517debb3ee454a1c91097955780697-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum                                                                                      
Trying other mirror.                                                                                                                           
http://centos.brnet.net.br/centos/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum                                                                                      
Trying other mirror.                                                                                                                           
http://centos.brnet.net.br/centos/7.6.1810/os/x86_64/repodata/6614b3605d961a4aaec45d74ac4e5e713e517debb3ee454a1c91097955780697-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum                                                                                           
Trying other mirror.                                                                                                                           
http://centos.usetelecom.com.br/centos/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum                                                                                 
Trying other mirror.                                                                                                                           
http://mirror.ufscar.br/centos/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum                                                                                         
Trying other mirror.                                                                                                                           
http://centos.brisanet.com.br/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum                                                                                          
Trying other mirror.                                                                                                                           
http://mirror.ci.ifes.edu.br/centos/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum                                                                                    
Trying other mirror.                                                                                                                           
http://mirror.ufam.edu.br/centos/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum                                                                                       
Trying other mirror.                                                                                                                           
http://mirror.globo.com/centos/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum                                                                                         
Trying other mirror.                                                                                                                           
http://centos.ufes.br/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum                                                                                                  
Trying other mirror.                                                                                                                           
http://mirror.facom.ufms.br/centos/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum                                                                                     
Trying other mirror.                                                                                                                           
http://linorg.usp.br/CentOS/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum                                                                                            
Trying other mirror.                                                                                                                           
http://centos.brnet.net.br/centos/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum                                                                                      
Trying other mirror.                                                                                                                           
http://centos.usetelecom.com.br/centos/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum                                                                                 
Trying other mirror.                                                                                                                           
http://centos.brisanet.com.br/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum                                                                                          
Trying other mirror.                                                                                                                           
http://mirror.ci.ifes.edu.br/centos/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum                                                                                    
Trying other mirror.                                                                                                                           
http://mirror.ufam.edu.br/centos/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum                                                                                       
Trying other mirror.                                                                                                                           
http://mirror.globo.com/centos/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum                                                                                         
Trying other mirror.                                                                                                                           
http://centos.ufes.br/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum                                                                                                  
Trying other mirror.                                                                                                                           
http://mirror.facom.ufms.br/centos/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum                                                                                     
Trying other mirror.                                                                                                                           
http://mirror.ufscar.br/centos/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum                                                                                         
Trying other mirror.                                                                                                                           
http://linorg.usp.br/CentOS/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum                                                                                            
Trying other mirror.                                                                                                                           
http://centos.brnet.net.br/centos/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum                                                                                      
Trying other mirror.                                                                                                                           
http://centos.usetelecom.com.br/centos/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum                                                                                 
Trying other mirror.                                                                                                                           
http://mirror.ufscar.br/centos/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum                                                                                         
Trying other mirror.                                                                                                                           
http://centos.brisanet.com.br/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum                                                                                          
Trying other mirror.                                                                                                                           
http://mirror.ci.ifes.edu.br/centos/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum                                                                                    
Trying other mirror.                                                                                                                           
http://mirror.ufam.edu.br/centos/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum                                                                                       
Trying other mirror.                                                                                                                           
http://mirror.globo.com/centos/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum                                                                                         
Trying other mirror.                                                                                                                           
http://centos.ufes.br/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum                                                                                                  
Trying other mirror.                                                                                                                           
http://mirror.facom.ufms.br/centos/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum                                                                                     
Trying other mirror.                                                                                                                           

 One of the configured repositories failed (CentOS-7 - Updates),                                                                               
 and yum doesn't have enough cached data to continue. At this point the only                                                                   
 safe thing yum can do is fail. There are a few ways to work "fix" this:                                                                       

     1. Contact the upstream for the repository and get them to fix the problem.                                                               

     2. Reconfigure the baseurl/etc. for the repository, to point to a working                                                                 
        upstream. This is most often useful if you are using a newer                                                                           
        distribution release than is supported by the repository (and the                                                                      
        packages for the previous distribution release still work).                                                                            

     3. Run the command with the repository temporarily disabled                                                                               
            yum --disablerepo=updates ...                                                                                                      

     4. Disable the repository permanently, so yum won't use it by default. Yum                                                                
        will then just ignore the repository until you permanently enable it                                                                   
        again or use --enablerepo for temporary usage:                                                                                         

            yum-config-manager --disable updates                                                                                               
        or                                                                                                                                     
            subscription-manager repos --disable=updates                                                                                       

     5. Configure the failing repository to be skipped, if it is unavailable.                                                                  
        Note that yum will try to contact the repo. when it runs most commands,                                                                
        so will have to try and fail each time (and thus. yum will be be much                                                                  
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=updates.skip_if_unavailable=true

failure: repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2 from updates: [Errno 256] No more mirrors to try.
http://linorg.usp.br/CentOS/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
http://centos.brnet.net.br/centos/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
http://centos.usetelecom.com.br/centos/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
http://mirror.ufscar.br/centos/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
http://centos.brisanet.com.br/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
http://mirror.ci.ifes.edu.br/centos/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
http://mirror.ufam.edu.br/centos/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
http://mirror.globo.com/centos/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
http://centos.ufes.br/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
http://mirror.facom.ufms.br/centos/7.6.1810/updates/x86_64/repodata/65b728bb44786c3cfb7b7b8ac9eaf86217c43cdef1560c939dadb7860aaf042a-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
The command '/bin/sh -c yum update &&     yum upgrade -y' returned a non-zero code: 1`

I also tried to add:
`RUN yum --enablerepo=base clean metadata`

to the dockerfile with no luck. What might I be missing?

**Comment by mdedonno1337** [comment]
Working perfectly fine on my side, with european repos.
The problem seems to come from the brazilian repo, can not reproduce the problem on my side.
Try to replace the `yum update && yum upgrade -y` command with `yum update` and let me know.

**Comment by vfbsilva** [comment]
The problem is different as expected. I've tried your suggestion It still fails, same error.
Then I decided to modify the docker file:
`################################################################################
#
#   Builder environnement
#
################################################################################

FROM centos as builder
LABEL maintainer "Marco.DeDonno@unil.ch"
RUN sed -i 's/enabled=1/enabled=0/g' /etc/yum/pluginconf.d/fastestmirror.conf
ADD NFIQ2.tgz /

RUN yum update && \
    yum upgrade -y
 
RUN yum group install -y "Development Tools" && \
    yum install -y cmake

RUN cd /NFIQ2/libOpenCV && \
    cmake -D CMAKE_MAKE_PROGRAM=make /NFIQ2/OpenCV/
    
RUN make -C /NFIQ2/libOpenCV \
    opencv_core opencv_ts opencv_imgproc opencv_highgui opencv_flann \
    opencv_features2d opencv_calib3d opencv_ml opencv_video opencv_objdetect \
    opencv_contrib opencv_nonfree opencv_gpu opencv_photo opencv_stitching opencv_videostab

RUN make -C /NFIQ2/NFIQ2/

ENV LD_LIBRARY_PATH=/NFIQ2/biomdi/common/lib:/NFIQ2/biomdi/fingerminutia/lib:/NFIQ2/libOpenCV/lib

################################################################################
#
#   Running environnement
#
################################################################################

FROM centos

COPY --from=builder /NFIQ2/NFIQ2/bin/ /NFIQ2/NFIQ2/bin/
COPY --from=builder /NFIQ2/biomdi/common/lib/ /NFIQ2/biomdi/common/lib/
COPY --from=builder /NFIQ2/biomdi/fingerminutia/lib/ /NFIQ2/biomdi/fingerminutia/lib/
COPY --from=builder /NFIQ2/libOpenCV/lib/ /NFIQ2/libOpenCV/lib/

COPY --from=builder /NFIQ2/complianceTestSet/ /NFIQ2/complianceTestSet/

ENV LD_LIBRARY_PATH=/NFIQ2/libOpenCV/lib:/NFIQ2/biomdi/common/lib:/NFIQ2/biomdi/fingerminutia/lib`


`docker  build .              
Sending build context to Docker daemon  199.4MB
Step 1/17 : FROM centos as builder
 ---> 67fa590cfc1c
Step 2/17 : LABEL maintainer "Marco.DeDonno@unil.ch"
 ---> Using cache
 ---> bf512cd9c7e1
Step 3/17 : RUN sed -i 's/enabled=1/enabled=0/g' /etc/yum/pluginconf.d/fastestmirror.conf
 ---> Using cache
 ---> 802c5caa95cb
Step 4/17 : ADD NFIQ2.tgz /
 ---> Using cache
 ---> bb207ec9ad3e
Step 5/17 : RUN yum update &&     yum upgrade -y
 ---> Running in 20016f7b9108
Loaded plugins: ovl


 One of the configured repositories failed (Unknown),                                                                                          
 and yum doesn't have enough cached data to continue. At this point the only                                                                   
 safe thing yum can do is fail. There are a few ways to work "fix" this:                                                                       

     1. Contact the upstream for the repository and get them to fix the problem.                                                               

     2. Reconfigure the baseurl/etc. for the repository, to point to a working                                                                 
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=<repoid> ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>
        or
            subscription-manager repos --disable=<repoid>

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot find a valid baseurl for repo: base/7/x86_64
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container error was
14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
The command '/bin/sh -c yum update &&     yum upgrade -y' returned a non-zero code: 1`
So the problem are not the fast repos.

**Comment by vfbsilva** [comment]
Same error. I've modified the docker file:
`
FROM centos as builder
LABEL maintainer "Marco.DeDonno@unil.ch"
RUN sed -i 's/enabled=1/enabled=0/g' /etc/yum/pluginconf.d/fastestmirror.conf
ADD NFIQ2.tgz /

RUN yum update && \
    yum upgrade -y
 
RUN yum group install -y "Development Tools" && \
    yum install -y cmake

RUN cd /NFIQ2/libOpenCV && \
    cmake -D CMAKE_MAKE_PROGRAM=make /NFIQ2/OpenCV/
    
RUN make -C /NFIQ2/libOpenCV \
    opencv_core opencv_ts opencv_imgproc opencv_highgui opencv_flann \
    opencv_features2d opencv_calib3d opencv_ml opencv_video opencv_objdetect \
    opencv_contrib opencv_nonfree opencv_gpu opencv_photo opencv_stitching opencv_videostab

RUN make -C /NFIQ2/NFIQ2/

ENV LD_LIBRARY_PATH=/NFIQ2/biomdi/common/lib:/NFIQ2/biomdi/fingerminutia/lib:/NFIQ2/libOpenCV/lib



FROM centos

COPY --from=builder /NFIQ2/NFIQ2/bin/ /NFIQ2/NFIQ2/bin/
COPY --from=builder /NFIQ2/biomdi/common/lib/ /NFIQ2/biomdi/common/lib/
COPY --from=builder /NFIQ2/biomdi/fingerminutia/lib/ /NFIQ2/biomdi/fingerminutia/lib/
COPY --from=builder /NFIQ2/libOpenCV/lib/ /NFIQ2/libOpenCV/lib/

COPY --from=builder /NFIQ2/complianceTestSet/ /NFIQ2/complianceTestSet/

ENV LD_LIBRARY_PATH=/NFIQ2/libOpenCV/lib:/NFIQ2/biomdi/common/lib:/NFIQ2/biomdi/fingerminutia/lib
`

And it still fails. But now fastest mirrors is not loaded.

**Comment by mdedonno1337** [comment]
Have you tried the steps 3, 4 and 5 ?
In any case, this is due to a problem with the repos used on your side, not the Dockerfile itself.

**Comment by vfbsilva** [comment]
What mirrors are you using?

**Comment by vfbsilva** [comment]
Your idea did work!

```
################################################################################
#
#   Builder environnement
#
################################################################################

FROM centos as builder
LABEL maintainer "Marco.DeDonno@unil.ch"
RUN sed -i 's/enabled=1/enabled=0/g' /etc/yum/pluginconf.d/fastestmirror.conf
ADD NFIQ2.tgz /

#RUN yum update && \
#    yum upgrade -y
RUN  yum update

RUN yum group install -y "Development Tools" && \
    yum install -y cmake

RUN cd /NFIQ2/libOpenCV && \
    cmake -D CMAKE_MAKE_PROGRAM=make /NFIQ2/OpenCV/
    
RUN make -C /NFIQ2/libOpenCV \
    opencv_core opencv_ts opencv_imgproc opencv_highgui opencv_flann \
    opencv_features2d opencv_calib3d opencv_ml opencv_video opencv_objdetect \
    opencv_contrib opencv_nonfree opencv_gpu opencv_photo opencv_stitching opencv_videostab

RUN make -C /NFIQ2/NFIQ2/

ENV LD_LIBRARY_PATH=/NFIQ2/biomdi/common/lib:/NFIQ2/biomdi/fingerminutia/lib:/NFIQ2/libOpenCV/lib

################################################################################
#
#   Running environnement
#
################################################################################

FROM centos

COPY --from=builder /NFIQ2/NFIQ2/bin/ /NFIQ2/NFIQ2/bin/
COPY --from=builder /NFIQ2/biomdi/common/lib/ /NFIQ2/biomdi/common/lib/
COPY --from=builder /NFIQ2/biomdi/fingerminutia/lib/ /NFIQ2/biomdi/fingerminutia/lib/
COPY --from=builder /NFIQ2/libOpenCV/lib/ /NFIQ2/libOpenCV/lib/

COPY --from=builder /NFIQ2/complianceTestSet/ /NFIQ2/complianceTestSet/

ENV LD_LIBRARY_PATH=/NFIQ2/libOpenCV/lib:/NFIQ2/biomdi/common/lib:/NFIQ2/biomdi/fingerminutia/lib
```
